config/routes.rb
Liveitapp::Application.routes.draw do
  
  resources :tasks

  resources :entries
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect("/")
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  match 'entries/:id/liveit', to: 'tasks#create', as: 'liveit'
  match 'today', to: 'entries#today', as: 'today'
  
  root :to => 'entries#today'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :author, :content, :title, :verse_content, :verse_reference, :verse_translation
  
  has_many :tasks, :dependent => :destroy
  has_many :users, :through => :tasks
  
  validates_presence_of :title, :content, :verse_content, :verse_reference, :verse_translation
    
  validates_length_of :verse_translation, :within => 1..5
  
  default_scope order: 'id ASC'
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :entry
  
  # attr_accessible :user_id, :entry_id
 
  validates_presence_of :user_id, :entry_id
  validates_uniqueness_of :user_id, :scope => :entry_id, :message => "has already completed this entry."
  
  default_scope order: 'created_at DESC'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  
  has_many :tasks, :dependent => :destroy
  has_many :entries, :through => :tasks
  
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.image_url = auth["info"]["image"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
  
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    helper_method :current_user
    
    def user_signed_in?
      return true if current_user
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :notice => 'You need to sign in for access to this page.'
      end
    end
    
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
  
  def today
   # Choose random entry - based on today's date. Use offset to ensure that record exists.
   @entry = Entry.offset(Random.new(Time.now.beginning_of_day.to_i).rand(Entry.count)).first
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    # Line below will raise a page showing the full response of omniauth - good for debug.
    # raise env["omniauth.auth"].to_yaml
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in. Hello #{current_user.name}."
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    # Before_filter authenticate_user! checks that user is logged in first!
    @task.user_id = current_user.id || nil
    begin
      # Check for valid entry record
      Entry.find(params[:id])
      @task.entry_id = params[:id] || nil

      respond_to do |format|
        if @task.save
          format.html { redirect_to entry_path(@task.entry_id), notice: 'Task was successfully created.' }
          format.json { render json: @task.entry, status: :created, location: @task.entry }
        else
          format.html { redirect_to entry_path(@task.entry_id), notice: "You have already completed this entry." }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    rescue ActiveRecord::RecordNotFound
      @task.errors.add :entry, "Entry is invalid"
      respond_to do |format|
        format.html { redirect_to entries_path, notice: "Entry is invalid" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_entry.html.erb
<div class="article">
  <div class="tag tag_red">
    <div class="tagvalue">
	    <h3><%= @entry.id %></h3>
		  <p>DAY</p>
    </div>
  </div>

  <% if @entry.users.include?(current_user) %>
    <div class="tag tag_green tag_second">
      <div class="tagvalue">
  	    <h3></h3>
  		  <p>&nbsp;</p>
      </div>
    </div>
  <% end %>
  
  <h2><%= link_to @entry.title, entry %></h2>
  
  <p><%= @entry.content %><br /><br />

    <em><%= @entry.verse_content %></em> 
    (<%= link_to @entry.verse_reference + " " + @entry.verse_translation, "http://www.biblegateway.com/passage/?version=#{@entry.verse_translation}&search=#{@entry.verse_reference}", target: "_blank" %>)
  </p>
 
  <% if @entry.users.include?(current_user) %>
    <span class="bigbtn2 success">You've lived this out!</span>
  <% else %>
  	<%= link_to "LiveIt", liveit_path(@entry), class: "bigbtn2" %>
  <% end %>
  </div>

  <!-- Sharing -->
  <div id="sharing">
    <div id="sharecontent">
  	  <br />
  	  <div id="share" class="hidden">
  	    <a href="#" class='zocial facebook'>Share on Facebook</a>
        <a href="#" class='zocial twitter'>Share on Twitter </a>
      </div>

      <div class="social">
        <%= pluralize(@entry.users.count, "person") %> lived this out.<br />
        <% @entry.users.first(10).each do |user| %>
          <%= image_tag("#{user.image_url}", class: "user user_#{user.name}") %> 
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :verse_reference %><br />
    <%= f.text_field :verse_reference %>
  </div>
  <div class="field">
    <%= f.label :verse_translation %><br />
    <%= f.text_field :verse_translation %>
  </div>
  <div class="field">
    <%= f.label :verse_content %><br />
    <%= f.text_area :verse_content, rows: 3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing All Entries</h1>
<%= link_to 'Add New Entry', new_entry_path %>

<% @entries.each do |entry| %>
  
<div class="article">
  <div class="tag tag_red">
    <div class="tagvalue">
      <p>Day</p>
	    <h3><%= entry.id %></h3>
    </div>
  </div>
    
  <% if entry.users.include?(current_user) %>
    <div class="tag tag_green tag_second">
      <div class="tagvalue">
  	    <h3></h3>
  		  <p>&nbsp;</p>
      </div>
    </div>
  <% end %>
  
  <h2><%= link_to entry.title, entry %></h2>
  
  <p><%= entry.content %><br /><br />

    <em><%= entry.verse_content %></em> 
    (<%= link_to entry.verse_reference + " " + entry.verse_translation, "http://www.biblegateway.com/passage/?version=#{entry.verse_translation}&search=#{entry.verse_reference}", target: "_blank" %>)
  </p>

	<% if entry.users.include?(current_user) %>
    <span class="bigbtn2 success">You've lived this out!</span>
  <% else %>
  	<%= link_to "LiveIt", liveit_path(entry), class: "bigbtn2" %>
  <% end %>
  
  </div>

  <!-- Sharing -->
  <div id="sharing">
    <div id="sharecontent">
  	  <br />
  	  <div id="share" class="hidden">
  	    <a href="#" class='zocial facebook'>Share on Facebook</a>
        <a href="#" class='zocial twitter'>Share on Twitter </a>
      </div>

      <div class="social">
        <%= pluralize(entry.users.count, "person") %> lived this out.<br />
        <% entry.users.first(10).each do |user| %>
          <%= image_tag("#{user.image_url}", class: "user user_#{user.name}") %> 
        <% end %>
      </div>
    </div>
  </div>
</div>    
<% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<%= render :partial => "entry" %>

<%= link_to "Show all entries", entries_path %> 

app/views/entries/today.html.erb
<aside class="intro">
  <header>
    <h1>Want to live out your faith?</h1>
  </header>
	<content>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
	</content>

  <div id="divider"></div>
</aside>

<h2>Today's Entry</h2>

<%= render :partial => "entry" %>

<%= link_to "Show all entries", entries_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiveIt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//use.typekit.net/ubf7xnn.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body class="body">
  <header>
    <%= link_to image_tag("liveit.png", width: 300), root_url, class: "logo left" %>
    	<nav class="right">
        <% if current_user %>
          <%# image_tag("http://placehold.it/50x50", class: "right") %>
          <%= image_tag("#{current_user.image_url}", class: "right") %>
          
          <p class="left">
            Signed in as <%= current_user.name %> (via <%= current_user.provider %>)<br />
            <%= link_to "Sign out", signout_path %>
          </p>
        <% else %>
            <%= link_to "Sign In via Twitter", "/auth/twitter", class: "zocial twitter" %><br /> <%= link_to "Sign In via Facebook", "/auth/facebook", class: "zocial facebook" %> 
        <% end %>  
      </nav>
      <div id="divider" class="clear"></div>
  </header>

  <section class="content">
    <% if flash[:notice] %>
      <div id="flash">
        <br />
        <br />
        <div class="notice"><%= flash[:notice] %></div>
      </div>
    <% end %>
  
    <%= yield %>
  
    <div id="divider"></div>
  </section>
  
  <footer>
     &copy; 2012<%= link_to "mitchwd.com", "http://www.mitchwd.com" %> 
    <%= link_to "Home", root_url, class: "nav" %> 
    <%= link_to "Entries", entries_path, class: "nav" %> 
    <%= link_to "Tasks", tasks_path, class: "nav" %> 
  </footer>

</body>
</html>  

app/views/tasks/index.html.erb
<h1>Task Timeline</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.user.name %> completed <%= link_to task.entry.title + " (Day #{ task.entry.id })", task.entry %>  <span><%= time_ago_in_words(task.created_at) %> ago</span></li>
  <% end %>
</ul>